### ISSUE TITLE
bug:标题中的旋转动画似乎依赖于valaxy-addon-meting的css

### ISSUE THREAD

**Issue by BlueflameLi** [WRXinYue/valaxy-theme-sakura#17]
![image](https://github.com/user-attachments/assets/ab61bfac-4809-4848-8374-bfce6b7140f2)
`theme/components/SakuraNavbarBrand.vue`
```scss
      span:nth-of-type(2) {
        animation: rotate 1s linear infinite;
      }
```
这里的`@keyframes rotate`使用的是APlayer.min.css里的
