### ISSUE TITLE
Bug:追番列表无法切换Bilibili和Bangumi

### ISSUE THREAD

**Issue by BlueflameLi** [WRXinYue/valaxy-theme-sakura#18]
```scss
// theme/styles/plugins/bangumi.scss
.bbc-header-platform {
  /** 0 elements **/
  &:not(:has(*)) {
    display: none;
  }

  /** 1 elements **/
  &:has(> :last-child:nth-child(1)) {
    display: none;
  }

  /** >= 2 elements **/
  &:has(> :last-child:nth-child(2)) {
    display: flex;
  }
}
```
![image](https://github.com/user-attachments/assets/b75858f2-b276-48eb-8d5a-812e18cb1716)
`bbc-header-platform`下还有一层`bbc-tabs`，从始至终都只有这么一个元素，只会触发一个元素时的隐藏，应该用`bbc-tabs`
