### ISSUE TITLE
Bug: 首页Banner，hover时filter-grid疯狂闪烁

### ISSUE THREAD

**Issue by BlueflameLi** [WRXinYue/valaxy-theme-sakura#20]
在线demo里就可以看到，把鼠标移到横幅上，然后网格就开始疯狂闪烁，貌似是这个动画的问题
```scss
// SakuraHero.vue
.banner-style.filter-grid:hover::before {
    background: linear-gradient(
      to bottom,
      transparent,
      transparent 50%,
      fadeout(oklch(25.2% 0 0), 50) 50%,
      fadeout(oklch(25.2% 0 0), 50)
    );
    animation: wobble 250ms linear infinite;
    background-size: 100% 4px;
  }
```
